### ISSUE TITLE
Episode image in root folder

### ISSUE THREAD

**Issue by EdwarDDay** [ben-xo/dir2cast#61] opened 2022-08-12 22:40 UTC
Hi, I'm trying to setup a podcast in a subfolder.

My problem is, that `dir2cast` extracts the `.jpg` covers from the `.mp3` files in folder with `dir2cast.php` and not in the folder with the mp3 files. But in the rss feed the cover image urls point to the correct folder.

Do I need to configure something additionally?

current structure:
```
/var/www/dir2cast.php
/var/www/dir2cast.ini
/var/www/episode_001.jpg # extracted by dir2cast.php
/var/www/podcast/dir2cast.ini
/var/www/podcast/episode_001.mp3
```
wanted structure
```
/var/www/dir2cast.php
/var/www/dir2cast.ini
/var/www/podcast/dir2cast.ini
/var/www/podcast/episode_001.mp3
/var/www/podcast/episode_001.jpg # extracted by dir2cast.php
```

**Comment by ben-xo** [comment] 2022-08-15 09:18
Thank you for this bug report! That is certainly not the intended behaviour, and looks like a bug to me.

In the mean time if you move the files manually they should serve correctly. But I'll see what I can do fix the bug.

**Comment by ben-xo** [comment] 2022-08-24 09:20
This is now fixed in v1.35, with a test case added. Thanks again for reporting this!

**Comment by ben-xo** [comment] 2022-08-24 09:21
(although I would appreciate any feedback to confirm it works properly!)

**Closed** 2022-08-24 09:22 UTC
Labels: In Testing, Bug

**Comment by EdwarDDay** [comment] 2022-08-25 07:54
I checked it and it looks like it's working now. Thank you
